spring:
  application:
     name: DEFAULT-CONFIG
eureka:
  client:
    register-with-eureka: true       # ğŸ‘ˆ This will register your service with Eureka
    fetch-registry: true             # ğŸ‘ˆ Enables fetching registry information from Eureka Server
    service-url:
      defaultZone: http://localhost:8761/eureka/   # ğŸ‘ˆ Eureka Server URL
  instance:
    prefer-ip-address: true
