eureka:
  client:
    register-with-eureka: true        # Registers this service with Eureka
    fetch-registry: true              # Fetches registry information from Eureka Server
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka Server URL
  instance:
    prefer-ip-address: true           # Use IP instead of hostname for registration

